"""add company_tickers

Revision ID: 3a912abd4804
Revises:
Create Date: 2026-10-07 16:31:19.633585

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a912abd4804"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_tickers",
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("cik", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("ticker", name=op.f("pk_company_tickers")),
    )
    op.create_index(op.f("ix_company_tickers_cik"), "company_tickers", ["cik"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_company_tickers_cik"), table_name="company_tickers")
    op.drop_table("company_tickers")
    # ### end Alembic commands ###
