"""add filings

Revision ID: 57f645bbf823
Revises: 3a912abd4804
Create Date: 2026-10-08 22:31:28.759328

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57f645bbf823"
down_revision: str | Sequence[str] | None = "3a912abd4804"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filings",
        sa.Column("accession_no", sa.String(length=20), nullable=False),
        sa.Column("cik", sa.BigInteger(), nullable=False),
        sa.Column("form_type", sa.String(length=10), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=False),
        sa.Column("report_date", sa.Date(), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("primary_document", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="discovered", nullable=False),
        sa.Column("failed_stage", sa.String(length=16), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("raw_object_key", sa.Text(), nullable=True),
        sa.Column("raw_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('discovered', 'downloaded', 'parsed', 'chunked', 'tagged', 'embedded', 'indexed', 'failed')",
            name=op.f("ck_filings_status"),
        ),
        sa.PrimaryKeyConstraint("accession_no", name=op.f("pk_filings")),
    )
    op.create_index(op.f("ix_filings_cik"), "filings", ["cik"], unique=False)
    op.create_index(op.f("ix_filings_fiscal_year"), "filings", ["fiscal_year"], unique=False)
    op.create_index(op.f("ix_filings_status"), "filings", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_filings_status"), table_name="filings")
    op.drop_index(op.f("ix_filings_fiscal_year"), table_name="filings")
    op.drop_index(op.f("ix_filings_cik"), table_name="filings")
    op.drop_table("filings")
    # ### end Alembic commands ###
